README.md
So others could follow the progress.
=> Add link to HTML Report WIP issue.

build.gradle, ci/build.sh, composer/build.gradle
=> Setup automatic publishing to Bintray (jcenter).

dependencies.gradle
https://github.com/ReactiveX/RxJava/releases/tag/v1.3.0
=> Update RxJava 1.2.9 → 1.3.0.

README.md
This will break download instead of writing some wrong content to the file like 404 html page.
=> Add --fail to curl snippet.

composer/build.gradle, composer/src/main/kotlin/com/gojuno/composer/html/HtmlFullSuite.kt, composer/src/main/kotlin/com/gojuno/composer/html/HtmlFullTest.kt, composer/src/main/kotlin/com/gojuno/composer/html/HtmlReport.kt, composer/src/main/kotlin/com/gojuno/composer/html/HtmlShortTest.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlFullSuiteSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlFullTestSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlReportSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlShortTestSpec.kt, composer/src/test/kotlin/com/gojuno/composer/test.kt, dependencies.gradle
=> Generate separate json files per test.

ci/build.sh
=> Add --rm flag to 'docker run'.

.gitignore, ci/build.sh, composer/src/main/kotlin/com/gojuno/composer/Main.kt, composer/src/main/kotlin/com/gojuno/composer/html/HtmlFullSuite.kt, composer/src/main/kotlin/com/gojuno/composer/html/HtmlFullTest.kt, composer/src/main/kotlin/com/gojuno/composer/html/HtmlReport.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlFullSuiteSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlFullTestSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlReportSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlShortTestSpec.kt, html-report/layout/index.html
=> Integrate HTML report with Composer!

ci/docker/entrypoint.sh
=> Remove logging from entrypoint.sh.

composer/src/main/kotlin/com/gojuno/composer/Main.kt
=> Print duration of HTML report generation.

html-report/src/components/SearchBar.js, html-report/src/components/Suite.js
Basically, I have just moved the filtering functionality (and the view) into the search component, which is not quite elegant, but at the moment is a working solution ¯\_(˶′◡‵˶)_/¯
=> Search fix

html-report/layout/log-entry.html, html-report/styles/_custom.scss
=> Fix long lines breaking the layout in logs #56

html-report/src/components/SuitesList.js, html-report/src/components/TestItem.js, html-report/styles/_custom.scss
=> Add titles to screenshots #54

.gitignore, composer/src/main/kotlin/com/gojuno/composer/html/HtmlFullTest.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlFullTestSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlReportSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlShortTestSpec.kt
Related to #76 and closes #54.
=> Generate proper JSON to display screenshots with titles.

README.md
=> Add note about Swarmer to the README.

README.md
These params were added in the following PRs:
* https://github.com/gojuno/composer/pull/85
* https://github.com/gojuno/composer/pull/94
=> Updated README.md for `--devices` and `--device-pattern`

composer/src/main/kotlin/com/gojuno/composer/Args.kt, composer/src/main/kotlin/com/gojuno/composer/Main.kt, composer/src/main/kotlin/com/gojuno/composer/TestRun.kt, composer/src/main/kotlin/com/gojuno/composer/html/HtmlReport.kt, composer/src/test/kotlin/com/gojuno/composer/ArgsSpec.kt
=> Reworked args, fixed issue with instrumentation args separated by commas

composer/src/main/kotlin/com/gojuno/composer/Instrumentation.kt, composer/src/test/kotlin/com/gojuno/composer/InstrumentationSpec.kt, composer/src/test/resources/instrumentation-output-assumption-violation.txt
First part of https://github.com/gojuno/composer/issues/112
Tests with violation are treated as Ignored, not Failed.
=> Change assumption violation instrumentation result from failed to ignored

composer/src/main/kotlin/com/gojuno/composer/Main.kt, composer/src/main/kotlin/com/gojuno/composer/html/HtmlDevice.kt, composer/src/main/kotlin/com/gojuno/composer/html/HtmlFullTest.kt, composer/src/main/kotlin/com/gojuno/composer/html/HtmlShortTest.kt, composer/src/test/kotlin/com/gojuno/composer/JUnitReportSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlDeviceSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlFullSuiteSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlFullTestSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlReportSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlShortSuiteSpec.kt, composer/src/test/kotlin/com/gojuno/composer/html/HtmlShortTestSpec.kt, dependencies.gradle, html-report/src/components/Suite.js, html-report/src/components/SuitesList.js, html-report/src/components/TestItem.js
Won't compile until commander 0.1.5 is released.
=> Add device name to HTML reports. Fixes #122.

dependencies.gradle
Upgrade commander version to 0.1.6 so that it can run in Windows.
Related:
https://github.com/trevjonez/composer-gradle-plugin/issues/13
https://github.com/gojuno/commander/issues/4
https://github.com/gojuno/commander/pull/14
=> Upgrade commander version to 0.1.6

README.md
I think that'll make it easier for people to understand what options are doing and how to customize them :)
=> Restructure list of options, add examples and defaults.

.travis.yml
=> Move releases deployment from internal Jenkins to Travis.
